# Generated by Django 5.0.2 on 2024-08-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('cover_image', models.ImageField(upload_to='covers/')),
                ('description', models.TextField()),
                ('num_chapters', models.PositiveIntegerField()),
                ('is_ongoing', models.BooleanField(default=True)),
                ('ranking', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('is_top', models.BooleanField(default=False)),
            ],
        ),
    ]
