# Generated by Django 5.0.2 on 2024-08-09 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novel',
            name='is_top',
        ),
    ]
