# Generated by Django 5.0.2 on 2024-08-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0002_remove_novel_is_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='is_top',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='novel',
            name='num_chapters',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='novel',
            name='ranking',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
