# Generated by Django 5.0.2 on 2024-08-12 14:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0003_novel_is_top_alter_novel_id_alter_novel_is_ongoing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Ongoing', max_length=50),
        ),
    ]
