# Generated by Django 5.0.2 on 2024-08-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0004_novel_created_date_novel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
