# Generated by Django 5.0.2 on 2024-08-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_novel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='num_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
