# Generated by Django 5.0.2 on 2024-08-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0008_alter_novel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(blank=True, to='novels.tag'),
        ),
    ]
