# Generated by Django 5.0.2 on 2024-08-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0010_remove_novel_num_ratings_alter_novel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='novel',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
