# Generated by Django 5.0.2 on 2024-09-05 14:51

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0028_alter_reply_comment_alter_reply_user_novelcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='novelcontent',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novels.novel'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='novelcontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
