# Generated by Django 5.0.2 on 2024-09-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0029_chapter_view_count_novelcontent_view_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='chapter_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
