# Generated by Django 5.0.2 on 2024-09-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0030_chapter_chapter_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
