# Generated by Django 5.0.2 on 2024-09-06 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0031_alter_novel_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='release_date',
            field=models.DateField(default=0),
        ),
    ]
