# Generated by Django 5.0.2 on 2024-09-06 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0033_alter_novel_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelcontent',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='novelcontent',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='novels.novel'),
        ),
        migrations.AlterModelTable(
            name='novelcontent',
            table='novels_novelcontent',
        ),
    ]
