# Generated by Django 5.0.2 on 2024-09-06 09:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0034_alter_novelcontent_content_alter_novelcontent_novel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelcontent',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
