# Generated by Django 5.0.2 on 2024-09-06 09:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0035_alter_novelcontent_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
