# Generated by Django 5.0.2 on 2024-09-06 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0037_alter_novelcontent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='novelcontent',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='novelcontent',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novels.novel'),
        ),
        migrations.AlterField(
            model_name='novelcontent',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
