# Generated by Django 5.0.2 on 2024-09-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0038_alter_novelcontent_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelcontent',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='novelcontent',
            unique_together={('novel', 'chapter_number')},
        ),
    ]
