# Generated by Django 5.0.2 on 2024-09-06 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0039_alter_novelcontent_view_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelcontent',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='novelcontent',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='novels.novel'),
        ),
    ]
