# Generated by Django 5.0.2 on 2024-09-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0042_bookmark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bookmarked_novels',
            field=models.ManyToManyField(related_name='bookmarked_by', to='novels.novel'),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='bookmarked_at',
        ),
    ]
