# Generated by Django 5.0.2 on 2024-09-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0045_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
