# Generated by Django 5.0.2 on 2024-09-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0048_alter_comment_parent_alter_reply_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
